name: app_table
description: A Flutter widget that displays a customizable table with headers and rows of data. It supports various customization options for styling and layout.
version: 0.0.3
repository: https://github.com/elrizwiraswara/app_table

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:

topics:
  - table
  - data-table
  - flutter-table
  - flutter-data-table